name: Code Quality

on:
  pull_request:
  push:
    branches: [ "master", "main", "develop" ]

jobs:
  php-cs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no

      - name: Run PHPStan (Static Analysis)
        run: vendor/bin/phpstan analyse --configuration=phpstan.neon --memory-limit=1G

      - name: Run Pint (Laravel Coding Standards)
        run: vendor/bin/pint --test
