name: Security Check

on:
  schedule:
    - cron: '0 3 * * 1' # Weekly on Monday
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: symfonycorp/security-checker-action@v4
